### ISSUE TITLE
Duplicated rows in PLOT table

### ISSUE THREAD

**Issue by danfosterfire** [hunter-stanke/rFIA#1]
Thanks for this package; it's really making the FIA data much more accessible! 

I have a question about the PLOT table produced by getFIA and readFIA. I used getFIA() to pull FIA plots from CA, OR, and NV which fell within a large AOI polygon (the range of sugar pine). When I read in the .csv files with readFIA(), the PLOT table has what look like duplicate rows: Every column is identical except for the final 'prev', which has value 0 for one row and 1 for the other. From what I can tell, 'prev' is an internal column created by rFIA and not part of the original FIA database. 

Am I correct in my belief that PLT_CN is the unique observation identifier for the PLOT table? Am I correct in assuming that there should only be one (unique) PLT_CN in the PLOT table, and that the duplicate rows are not intended behavior?

Here's my script which writes a PLOT.csv with duplicated-except-for-prev rows:

```{r}#
#  DEFINE AOI AND FETCH FIA DATA
#

#### setup #####################################################################

library(here)
library(rFIA)
library(tidyverse)
library(sf)
library(tmap)

# download FIA data for CA, OR, and NV. Write to a local directory.
#fia_all = 
#  getFIA(states = c('CA', 'OR', 'NV'),
#       dir = here::here('02-data',
#                        '00-source',
#                        'fia'))

# when re-running this script, just read the local version.
fia_all = 
  readFIA(here::here('02-data',
                     '00-source',
                     'fia'))

# pila range from Digital representation of "Atlas of United States Trees" by 
# Elbert L. Little, Jr.; digitized by Robert S. Thompson and accessed at 
# https://github.com/wpetry/USTreeAtlas. 
pila_range = 
  sf::st_read(here::here('02-data',
                       '00-source',
                       'ustreeatlas',
                       'pinulamb.shp')) %>%
  # the original crs, as described in the metadata for the digitized version
  sf::st_set_crs('+proj=longlat +datum=NAD27 +no_defs') %>%
  # the CRS of the FIA data
  sf::st_transform(crs = sf::st_crs('+proj=longlat +datum=WGS84 +no_defs'))


# clip FIA data to just the AOI
fia_aoi = 
  fia_all %>%
  rFIA::clipFIA(mostRecent = FALSE,
                mask = pila_range)

# save the clipped database locally
rFIA::writeFIA(fia_aoi,
               dir = here::here('02-data',
                                '01-preprocessed',
                                'fia'))````

**Comment by hunter-stanke** [comment]
Danny, 

Glad to hear you are putting rFIA to work, and thanks for reaching out! 

You are correct in that PLT_CN is a unique ID for observations in the PLOT table, and hence there should be a single PLT_CN for each visit (i.e., no duplicates). The issue of duplicated rows originated in `clipFIA` - I just pushed up a fix. For the example you listed, you should now find 11,639 unique plot visits recorded in PLOT (no duplicates).

If you reinstall `rFIA` from GitHub you should be set, but please let me know if anything acts up. I'm always happy to help!

Hunter
