### ISSUE TITLE
Increased support for merchantable tree volume estimation?

### ISSUE THREAD

**Issue by hunter-stanke** [hunter-stanke/rFIA#12]
I'm considering making some changes to rFIA that would substantially improve its capacity to estimate current tree volume. Right now, we can produce current tree volume estimates (i.e., net merchantable volume and sawlog volume) using the `biomass` function. However, I think it would be cleaner to simplify `biomass` to only produce tree biomass/carbon estimates and write a separate function that is focused exclusively on merchantable tree volume. I'd like to call it `volume`, but open to alternatives if this would cause conflicts with other commonly used packages - looks like `spatstat` and `cluster` also use it. 

In developing the new function, I'm proposing that we expand the scope of volume variables to include net, sound, and gross bole volume (cu. ft.) and saw log volume (cu. ft. and MBF via International 1/4" rule). This would nearly match EVALIDator's current capacity. 

Any strong feelings for or against the proposed changes? Of course the changes to `biomass` would be breaking, however I don't anticipate folks' workflows would have to be changed that much to account for it. Please let me know if that is not the case!

**Comment by bi0m3trics** [comment]
Just a suggestion, but if your firm on just using 'merica units for volume the variable names could be cuft and mbft... and then there'd be no conflict with spatstat etc. There's a precedent for that in other software... that or something along the lines of CCF and MBF, but then you'd be stuck with 100s and 1000s...

**Comment by hunter-stanke** [comment]
That's a great idea! 

Only reason we stick with Imperial is for consistency with EVALIDator, but now that we can spit out variances for population estimates it's pretty easy to convert back and forth. That being said, maybe it would be useful to give users the option up front. 

Thanks again!
