### ISSUE TITLE
Error in CARB_TOTAL_VAR calculations

### ISSUE THREAD

**Issue by badgley** [hunter-stanke/rFIA#13]
Running `carbon` with the variance flag set to true seems to be producing incorrect estimates of `CARB_TOTAL_VAR`. In my own comparisons, it looks like `CARB_TOTAL_VAR` is _always_ equal to `CARB_ACRE_VAR`.

Here is a minimal example:
```R
library(rFIA)
riMR <- clipFIA(fiaRI)
carbonTotal <- carbon(riMR, variance=TRUE, totals = TRUE)
all(carbonTotals$CARB_TOTAL_VAR == carbonTotals$CARB_ACRE_VAR)
```

The final call evaluates as true for me.

I peeked at the code is it seems that `caVar`, as opposed to `cVar` is returned for `CARB_TOTAL_VAR`
https://github.com/hunter-stanke/rFIA/blob/b1c0c3dfe5ef917295ed4124dc65264989c78002/R/carbon.R#L399

Happy to open a pull request if this is indeed an error.

**Comment by hunter-stanke** [comment]
Great catch! This is definitely an error on my end. If you want to open up a pull request I'll go ahead and merge. Happy to fix on my end too if that's easier.

**Comment by hunter-stanke** [comment]
Just merged your fix, thanks so much!
