### ISSUE TITLE
Using "real" plot coordinates

### ISSUE THREAD

**Issue by jgrn307** [hunter-stanke/rFIA#19]
If we get approval to have access to the true FIA plot coordinates (not the fuzzed ones), is there a procedure to replace the fuzzed ones with the real ones?

**Comment by hunter-stanke** [comment]
Sorry for the delayed reply! 

From what I remember of previous conversations, the true coordinates are added as variables to the PLOT table---where `LAT` and `LON` are the fuzzed/swapped coordinates, and something like `LAT_ACTUAL` and `LON_ACTUAL` are the true coordinates. I haven't personally seen the data with the true plot coordinates, so let me know if I'm wrong on this. 

If this is the case, however, you can simply replace `LAT` and `LON` in the PLOT table with `LAT_ACTUAL` and `LON_ACTUAL`, and rFIA won't know the difference. Assume that `db` is your FIA data with the true plot coordinates:
```
## Save a copy of the fuzzed/swapped coordinates, and overwrite LAT/LON with TRUE coordinates
db$PLOT <- db$PLOT %>%
   mutate(LAT_FUZZED = LAT,
               LON_FUZZED = LON,
               LAT = LAT_ACTUAL,
               LON = LON_ACTUAL)

## Now you can hand your modified db object to any rFIA function, and it should run without complaints
biomass(db, byPlot = TRUE, returnSpatial = TRUE)
```

Again, I'm not sure what the variables associated w/ the true plot coordinates are named (or if the data is delivered this way at all), so let me know if I'm wrong here! Thanks again.
