### ISSUE TITLE
readFIA and getFIA error

### ISSUE THREAD

**Issue by djj4tree** [hunter-stanke/rFIA#2]
I am trying to combine multiple states into one database. The getFIA function "getFIA(dir = "./Data", states=c("RI","ND"))" downloads the data fine, but when combining the tables it throws this error.

"Error in rbindlist(inTables[names(inTables) == uniqueNames[i]]) : 
  Item 42 has 52 columns, inconsistent with item 1 which has 72 columns. To fill missing columns use fill=TRUE."

It also happens in the same spot in the code for the readFIA function: readFIA(dir="./Data/")

I haven't been able to find the offending table that has inconsistent numbers of columns. 
I am only using the 'common' tables.

**Comment by hunter-stanke** [comment]
This is an odd one - I haven't been able to reproduce the error yet. Could you pass along your session info by typing `sessioninfo::session_info()`  into R and copy/pasting the output here?

Also which states are you attempting to merge? I see Rhode Island and North Dakota above, is that correct? Is `getFIA` working properly for a single state?

We'll get this taken care of, will just take a bit of investigation. Thanks for reporting!

**Comment by djj4tree** [comment]
I think I figured it out. The folder I was storing the data in had other csv files in it and I believe the function was trying to coerce an incorrect file into the rbind call. I reran the function downloading to a clean folder and the problem went away. Thanks!

**Comment by hunter-stanke** [comment]
Perfect, glad you're up and running! Always happy to help.
