### ISSUE TITLE
SEs for carbon

### ISSUE THREAD

**Issue by Picearubens** [hunter-stanke/rFIA#21]
The standard errors produced for the total carbon estimates seem much too small (>0.00001), but I could be wrong. Just want to make sure I'm representing the data correctly. 

<img width="418" alt="Capture" src="https://user-images.githubusercontent.com/9536645/130618735-a3fdba0f-577a-4464-832d-9c20bbfefe58.PNG">

car_ct_ag<-carbon(db, grpBy = c(COUNTYCD), polys = NULL, returnSpatial = FALSE,
                  byPool = TRUE, byComponent = FALSE, modelSnag = TRUE,
                  landType = "forest", method = "TI", lambda = NULL,
                  areaDomain = NULL, totals = TRUE, byPlot = FALSE,
                  nCores = 1)

#Looking at just total AGB for Addison County
car_ct_ag1<-car_ct_ag %>%
  full_join(ctcodes, by = c ("COUNTYCD" = "Code")) %>%
  filter(POOL == "AG_LIVE") %>%
  filter(County == "Addison")

**Comment by hunter-stanke** [comment]
Sorry for the (very) delayed reply here! I accidentally shut off my email notifications, and I'm just now seeing issues that were opened in August.

Those error estimates were certainly too small, that's an error on my end. I'm just finishing up a complete backend re-write of rFIA, and I've taken care of that issue in the process. 

Could you reinstall rFIA from GitHub using either `devtools::install_github("hunter-stanke/rFIA")` or `remotes::install_github("hunter-stanke/rFIA")`, and confirm the error has been fixed for your example? 

Again, I apologize for the delayed response.
