### ISSUE TITLE
vitalRates() for states with no TREE_GRM_BEGIN or SUBP_COND_CHNG_MTRX

### ISSUE THREAD

**Issue by KatieMurenbeeld** [hunter-stanke/rFIA#22]
I'm working with FIA data from Idaho and would like to use vitalRates to calculate diameter growth. However, Idaho does not have values in the the TREE_GRM_BEGIN or SUBP_COND_CHNG_MTRX tables, throwing this error. 

`vital_rates <- vitalRates(db, bySpecies = TRUE)`
`Error in FUN(X[[i]], ...) : Tables TREE_GRM_BEGIN, SUBP_COND_CHNG_MTRX not found in object db.`

Would there be a way to adjust for states that lack these tables? It looks like there are several other states that lack this data.

**Comment by hunter-stanke** [comment]
Hi Katie, 

Sorry for the (very) delayed response on my end - I've been out on medical leave. 

Unfortunately, FIA hasn't yet populated the GRM tables for most states in the Intermountain West region, which makes it impossible for us to replicate "standard" estimation routines (i.e., those implemented in EVALIDator) for these states. 

That being said, there are plot remeasurements available in all states except WY and the plot-level data can be used to estimate individual tree and stand-level growth rates. Unfortunately it's more complicated than simply using `vitalRates`, but it can be done. Let me know if this is still of interest and I can put together an example. 

Again, sorry for the delay!
