### ISSUE TITLE
Planning for release?

### ISSUE THREAD

**Issue by hadley** [hunter-stanke/rFIA#24]
On the CRAN version of rFIA, I see a failure with dev dtplyr:

``` r
library(rFIA)
fiaRI_mr <- clipFIA(fiaRI)
area(db = fiaRI_mr)
#> Error in fifelse(sum(aDI > 0, na.rm = TRUE), 1, 0): Argument 'test' must be logical.
```

<sup>Created on 2021-10-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

This is because dtplyr now translates `ifelse()` to `data.table::fifelse()`, which is stricter about the types of its arguments.

I don't see this error in the dev version, so I was wondering if you were planning to release soon? I don't want to break your package on CRAN by updating dtplyr.

**Comment by hunter-stanke** [comment]
Thanks Hadley! We're planning a release at the end of the week that will resolve the issues. 

Sorry for the delayed response, I've been on medical leave for a few months. 

Thanks again!
