### ISSUE TITLE
growMort function not recognizing all treeTypes

### ISSUE THREAD

**Issue by scotthllrd** [hunter-stanke/rFIA#25]
I am having an issue with the growMort() function returning error:

ct <- getFIA(states = 'MN', dir = '/path')
kl<-growMort(db = ct,
             bySpecies = TRUE,
             landType = 'timber',
             treeType = 'live',
             totals  = TRUE)
returns:
_Error: Can't subset columns that don't exist.
x Column `SUBPTYP_GRM` doesn't exist._

I am seeing the same error when trying treeType= 'dead'

However:
kl<-growMort(db = ct,
             bySpecies = TRUE,
             landType = 'timber',
             treeType = 'all',
             totals  = TRUE)

completes. This also completes with 'gs'

**Comment by hunter-stanke** [comment]
Hi Scott, 

This looks like a documentation/ error handling issue on my side - great catch!

 `growMort` should only accept `all` or `gs` as input to the `treeType` argument, but that was not previously reflected in our documentation. I've updated the docs and modified `growMort` to throw an error when receiving invalid inputs to `treeType`. 

You can install the updates from GitHub with `devtools::install_github("hunter-stanke/rFIA")`.
