### ISSUE TITLE
mergeSmallStrata(): 'buf' not 'buff' to id intensified PNW strata

### ISSUE THREAD

**Issue by kkralicek0** [hunter-stanke/rFIA#26]
I found my way to your `mergeSmallStrata` function when looking for options to automatically merge small-n strata. I've been working with the PNW FIA data (SQLite dbs from the DataMart) and noticed this function's code currently uses the string 'buff' when trying to identify intensified strata. When looking at STRATUM_DESCR, I see 'buf' (one f) and 'int', but not 'buff'. 

(Although I am not completely convinced 'buf|int' is sufficient to identify intensified strata: in the set of plots I am working with, the absence of 'buf|int' does not always correspond to plot.INTENSITY = 1. For example, STRATUMCD = 11 and EVALID = 531903.)

**Comment by hunter-stanke** [comment]
Great catch - that's definitely an error on my end. Thank you!

I certainly agree regarding 'buf|int'.  Ideally we would never rely on stratum descriptions to identify intensification or underlying motivations for stratification. Unfortunately though, we've been working on the small strata issue for a while, and haven't found a better alternative that's nationally-consistent (or consistently documented through time). The INTENSITY variable from PLOT always seems promising, but (1) the codes vary over time and from region-to-region, and (2) I still frequently end up with single plot-year strata across the US when using INTENSITY alone to identify intensification. 

All that said, I haven't dug into this in a couple months, and I very well could be missing something. If you find a cleaner alternative for the PNW (and would be willing to share), and I'd love to see it. Each region presents its own nuances w/ respect to stratification, but the PNW is generally a sticking point in terms of national consistency. So usually if a fix works for the PNW, it works for the remainder.
