### ISSUE TITLE
vitalRates grpBy = SUBP error

### ISSUE THREAD

**Issue by whalend** [hunter-stanke/rFIA#6]
I was exploring the `vitalRates` estimation and get an error when attempting to group by subplot:

`vitalRates(fiaRI,  landType = "forest", grpBy = SUBP,  byPlot = TRUE,  bySpecies = TRUE)`

> Error in checkForRemoteErrors(val) : 
>   one node produced an error: Column name `SUBP` must not be duplicated.

**Comment by hunter-stanke** [comment]
Sorry for the delayed response - been out of the office for few days. The error comes from changes in the new release of dplyr (v1.0.0). 

Just pushed up a fix - go ahead and reinstall with `devtools::install_github('hunter-stanke/rFIA')`. Should be set  from there. 

Thanks again!
