### ISSUE TITLE
getFIA with multiple states

### ISSUE THREAD

**Issue by engineerchange** [hunter-stanke/rFIA#7]
When combining states, getFIA appears to have an issue.

Example 1:
```
fiaNE <- rFIA::getFIA(states=c("CT","ME","MA","NH","RI","VT"))
```

Error reported:
```
Error in rbindlist(inTables[names(inTables) == uniqueNames[i]]) : 
  Class attribute on column 17 of item 3 does not match with column 17 of item 1.
```

Example 2:
```
fiaMid <- rFIA::getFIA(states=c("DE","MD"))
```

Error reported:
```
Error in rbindlist(inTables[names(inTables) == uniqueNames[i]]) : 
  Class attribute on column 17 of item 2 does not match with column 17 of item 1.
```

It's odd, but it does appear that anything else I try to load after this failure appreciates the same error; even a simple getFIA for a single state that works fine under a new RStudio session will produce the error above if run after one of the examples above, like:

```
fiaDE <- rFIA::getFIA(states="DE")
```

Version info:
```
packageVersion("rFIA")
[1] ‘0.2.3’
```

**Comment by hunter-stanke** [comment]
Thanks for reaching out! I apologize for the delayed response. 

I've given this a try on a few different machines, and haven't yet been able to reproduce the error. However, similar error messages are sometimes thrown when there are loose non-FIA csv files in the target directory. 

In the short-term, try updating rFIA from GitHub with `devtools::install_github('hunter-stanke/rFIA')` and re-running the above to download to a clean target directory. If it was a loose csv causing the error, this should take care of it. Longer-term, the next release of rFIA will provide a more robust fix for these issues (scope of `getFIA` and `readFIA` will be reduced to known FIA files). 

If this doesn't take care of the error, please let me know. Always happy to help!

Hunter

**Comment by engineerchange** [comment]
I tried using the recent 0.2.4 CRAN release, and then the GitHub version above. The problem occurred in all versions for me; I tested on both Mac and Windows environments.

Was able to confirm the bug with a bit more accuracy. Looks like it is related to a column not having the right data type because no data has ever existed on that column in some of the states; the column in question is MODIFIED_DATE in POP_PLOT_STRATUM_ASSGN.

``` r
library(tidyverse)

packageVersion("rFIA")
#> [1] '0.2.4'

failing_case<- rFIA::getFIA(states=c("DE","MD"))
#> Error in rbindlist(inTables[names(inTables) == uniqueNames[i]]): Class attribute on column 17 of item 2 does not match with column 17 of item 1.

fiaDE <- rFIA::getFIA(states=c("DE"))
fiaMD <- rFIA::getFIA(states=c("MD"))

fiaDE$POP_PLOT_STRATUM_ASSGN[,17] %>% as.data.frame() %>% distinct()
#>    .
#> 1 NA
fiaDE$POP_PLOT_STRATUM_ASSGN[,17] %>% class()
#> [1] "logical"

fiaMD$POP_PLOT_STRATUM_ASSGN[,17] %>% as.data.frame() %>% distinct()
#>            .
#> 1       <NA>
#> 2 2010-12-15
fiaMD$POP_PLOT_STRATUM_ASSGN[,17] %>% class()
#> [1] "IDate" "Date"
```

<sup>Created on 2020-09-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hunter-stanke** [comment]
Was finally able to reproduce the error, comes with an update of data.table to ‘1.13.0’. Also I appreciate the reprex, saves me a good amount time! As a temporary fix I've restricted `readFIA` (internally called by `getFIA`) from ever reading the MODIFIED_DATE column. A fresh install from GitHub should take care of it. 

This fix obviously isn't all that robust (i.e., there are probably lots of MODIFIED_DATE type columns in the FIADB). In the near future I'm planning to add an option to `readFIA` that will selectively drop all of FIA's internal use columns. That should hopefully prevent similar issues in the future _and_ come with the added benefit of improving memory efficiency (by quite a lot potentially).

Thanks again for reaching out with this!

**Comment by hunter-stanke** [comment]
Absolutely, always happy to help!
